import type { Entry } from "./catalog";
/** Historical names retained for discovery; unsourced regimens are deliberately unavailable. */
const queue: [string, string][] = [
  ["Dexmedetomidine", "Sedation"],
  ["Lorazepam", "Sedation"],
  ["Morphine", "Opioid"],
  ["Hydromorphone", "Opioid"],
  ["Alfentanil", "Opioid"],
  ["Methadone", "Opioid"],
  ["Meperidine (Demerol)", "Opioid"],
  ["Vecuronium", "Neuromuscular Blocker"],
  ["Pancuronium", "Neuromuscular Blocker"],
  ["Dobutamine", "Inotrope"],
  ["Milrinone", "Inotrope"],
  ["Labetalol", "Antihypertensive"],
  ["Esmolol", "Antihypertensive"],
  ["Hydralazine", "Antihypertensive"],
  ["Nicardipine", "Antihypertensive"],
  ["Clevidipine", "Antihypertensive"],
  ["Nitroglycerin", "Cardiovascular"],
  ["Sodium Nitroprusside", "Cardiovascular"],
  ["Amiodarone", "Antiarrhythmic"],
  ["Lidocaine (IV)", "Antiarrhythmic"],
  ["Adenosine", "Antiarrhythmic"],
  ["Atropine", "Anticholinergic"],
  ["Metoprolol (IV)", "Antihypertensive"],
  ["Idarucizumab (Praxbind)", "Reversal"],
  ["Ondansetron", "Antiemetic"],
  ["Dexamethasone", "Antiemetic"],
  ["Metoclopramide", "Antiemetic"],
  ["Droperidol", "Antiemetic"],
  ["Scopolamine (Patch)", "Antiemetic"],
  ["Promethazine", "Antiemetic"],
  ["Tranexamic Acid (TXA)", "Hemostatic"],
  ["Protamine", "Hemostatic"],
  ["Desmopressin (DDAVP)", "Hemostatic"],
  ["Calcium Chloride", "Emergency"],
  ["Sodium Bicarbonate", "Emergency"],
  ["Magnesium Sulfate", "Emergency"],
  ["Dantrolene", "Emergency"],
  ["Intralipid 20%", "Emergency"],
  ["Ketorolac", "Analgesic"],
  ["Acetaminophen IV (Ofirmev)", "Analgesic"],
  ["Gabapentin", "Analgesic"],
  ["Ketamine (analgesic)", "Analgesic"],
  ["Albuterol (Salbutamol)", "Bronchodilator"],
  ["Ipratropium", "Bronchodilator"],
];
export const pendingDrugEntries: Entry[] = queue.map(([title, category]) => ({
  id: `review-${title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-$/, "")}`,
  title,
  kind: "drug",
  summary: category,
  aliases: ["pending review"],
  sources: [],
  related: [],
  quick: [
    {
      title: "Monograph pending review",
      body: "This agent was present in the earlier reference library. Its historical doses and clinical claims have not been reconciled to an exact current product source. No prescribing values are supplied.",
    },
  ],
  learn: [
    {
      title: "Review requirements",
      body: "Select an exact product label and jurisdiction; reconcile indication, population, route, formulation, dose units, onset/duration context, contraindications, interactions and monitoring; obtain independent clinician/pharmacy approval with acceptance fixtures.",
    },
  ],
}));
export const pendingTopics: Entry[] = [
  [
    "mac-context",
    "MAC & age context",
    "Age, co-administered agents and exact volatile product",
    "The earlier fixed MAC, MAC-awake and MAC-BAR outputs are withheld. Use the exact product’s age-specific table; no universal consciousness or response threshold is generated.",
    ["drug-20", "drug-21", "drug-22"],
  ],
  [
    "ponv",
    "PONV prevention review",
    "Risk assessment, prophylaxis and rescue planning",
    "Discuss patient factors, prior nausea/motion sickness, smoking history, planned postoperative opioids and the local prevention/rescue pathway. Numeric scores, risk percentages and regimens require source-specific validation before release.",
    [],
  ],
  [
    "antibiotics",
    "Antibiotic prophylaxis review",
    "Procedure, allergy, timing and redosing context",
    "Confirm procedure-specific prophylaxis, allergy history, measured weight, renal function, administration timing, redosing and local susceptibility policy. Legacy dosing tables remain unavailable pending antimicrobial review.",
    [],
  ],
  [
    "opioid-equivalence",
    "Opioid equivalence review",
    "Route, tolerance and incomplete cross-tolerance",
    "No conversion ratio is supplied. Equianalgesic tables cannot be treated as direct prescriptions; route, prior exposure, incomplete cross-tolerance and special agents require individual specialist assessment.",
    ["drug-5", "drug-19"],
  ],
  [
    "local-products",
    "Local anesthetic product review",
    "Bupivacaine, ropivacaine, mepivacaine and other products",
    "Generic mg/kg ceilings for bupivacaine, ropivacaine, mepivacaine, chloroprocaine, tetracaine and prilocaine remain withheld. Exact route, product, indication, cumulative exposure and population must be independently reviewed. Only the narrowly scoped lidocaine label tool is supplied.",
    ["lidocaine", "last"],
  ],
].map(([id, title, summary, body, related]) => ({
  id: id as string,
  title: title as string,
  summary: summary as string,
  aliases: [],
  kind: "topic",
  sources: [],
  quick: [
    { title: "Preparation context — review pending", body: body as string },
  ],
  learn: [],
  related: related as string[],
}));
